### ISSUE TITLE
jme3 libraries in the NetBeans project libraries

### ISSUE THREAD

**Issue by jjrobinson** [salaxy/SailSim#30]
I have been looking for some project that models a sailboat so that I could learn & extend to make a realistic sailing MMO-RPG/RTS.  In doing so, I forked the project and opened in netbeans, but there are libraries missing that I cannot find.

I have the JME3 SDK installed, but these dependencies don't seem to be resolved with inclusion of the jme3 libs folder and jars.

Is there a specific packaging of the JMonkeyEngine jars that you are looking for with these two library references in the NB project:

"jme3"
"jme3-libraries"

![error_screen](https://cloud.githubusercontent.com/assets/6282545/5566595/11e2e264-8eeb-11e4-8d85-c885dc880ea4.png)

**Comment by salaxy** [comment]
I dont know the specific Problem, but i think maybe you need to have the Slick-Libaries to run it.
Slick is original for display, but the application is build as a Slick-Game and I used Eclipse for developing.

you need lwjgl.jar and slick.jar, addtionaly you need the native libs.

More help:
http://ninjacave.com/slickutilintro
http://slick.ninjacave.com/

I hope it is useful.

**Comment by jjrobinson** [comment]
Thank you very much for the tips.  I've been looking for a java based
sailing game / simulation to play with (or code my own).

**Comment by salaxy** [comment]
maybe if you can run it ... you could use it for a game, it is possible to create 3D or 2D games with slick in java. My simulation is still 2D and it use different wind directions in correct way, by it doesnt respect size of the boat or weight or something like that, it is still a prototype of a simulation.

**Comment by jjrobinson** [comment]
Andy,

That makes sense.  The 2d simulation needs to happen first though, before
any other aspects of a game can be developed.  Thanks again!
